name: Build new release and publish to PyPI

on:
  workflow_dispatch:

jobs:
  build:
    name: Build distribution from release branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: "release"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install repo and get version
        run: |
          python3 -m pip install .
          echo "version=$(python -c "import aepsych; print(aepsych.version.__version__)")" >> "$GITHUB_ENV"

      - uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Edit main version with dev appended
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s/^__version__ .*/__version__ = \""$version"+dev\"/" aepsych/version.py
          git add aepsych/version.py
          git commit -m "update dev version to "$version"+dev"
          gh pr create
